version: 2.1
jobs:
  build:
    docker:
      - image: vasppipoka/go_ninja:1.9
    steps:
      - run:
          name: Testando imagem docker
          command:
            echo "Hello World"
           