version: 2.1
jobs:
  build:
    docker:
      - image: golang:1.19.0-bullseye
    steps:
      - run:
          name: Clone Repo
          command: | 
            mkdir /go-ninja
            git clone https://github.com/vasppipoka/devops_test /go-ninja
            chmod 777 /go-ninja
      - run:
          name: build go-ninja
          command: |
            cd /go-ninja
            go mod init app
            go mod tidy
            go build -o main .
            ./main &
            curl -i http://127.0.0.1:8000/healthcheck
  test:
    docker:
      - image: golang:1.19.0-bullseye
    steps:
      - checkout 
      - run: 
          name: Testing Code
          command: |
            go test ./... -v 

workflows:
  build_and_test:
    jobs:
      - build
      - test
            
           